version: "3"

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    volumes:
      - matomo:/var/www/html
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html
      - ./matomo.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

volumes:
  db:
  matomo:
